project:
  type: website
  output-dir: _site/docs/
  resources:
    - labs/**
    - slides/**
    - course_materials/**
    - _site/images/**
  render:
    - _index.qmd
    - course_materials/tools/00_installation.qmd
    - course_materials/tools/01_git_github.qmd
    - course_materials/tools/02_quarto.qmd
    - course_materials/tools/03_reproducible_workflows.qmd

website:
  page-navigation: true
  sidebar:
    style: "docked"
    contents:
      - href: _index.qmd
        text: Home
      - href: course_materials/tools/00_installation.qmd
        text: 0 Software Installation
      - href: course_materials/tools/01_git_github.qmd
        text: 1 Git and GitHub
      - href: course_materials/tools/02_quarto.qmd
        text: 2 Quarto
      - href: course_materials/tools/03_reproducible_workflows.qmd
        text: 3 Reproducible Workflows

format:
  html:
    theme: sandstone
    css: _site/css/custom_style.css
    toc: true
    lightbox: true
    code-summary: "Show Code"
    code-fold: show
    code-tools: true
    embed-resources: true

execute:
  warning: false
  message: false
